{
    "openapi": "3.0.3",
    "info": {
        "title": "Blog API Documentation",
        "description": "This is a sample Blog API server based on the openAPI 3.0 specification",
        "contact": {
            "email": "nozami.id@gmail.com"
        },
        "license": {
            "name": "Blog API",
            "url": "http://localhost:8000"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://localhost:8000/api/v1"
        }
    ],
    "tags": [
        {
            "name": "User",
            "description": "Operation about User"
        },
        {
            "name": "Category",
            "description": "Operation about Category"
        }
    ],
    "paths": {
        "/register": {
            "post": {
                "tags": ["User"],
                "description": "Register new user",
                "requestBody": {
                    "description": "Created User Object",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["name", "username", "password"],
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "username": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "nozami": {
                                    "description": "Register User Nozami",
                                    "value": {
                                        "name": "nozami",
                                        "username": "nozami",
                                        "password": "password"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Register Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "nama": "nozami",
                                                "username": "nozami"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Validation Error",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Validation Error",
                                        "value": {
                                            "errors": {
                                                "username": [
                                                    "The username field is required.",
                                                    "The username has already been taken."
                                                ],
                                                "name": [
                                                    "The name field is required."
                                                ],
                                                "password": [
                                                    "The password field is required."
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "tags": ["User"],
                "description": "Login user",
                "requestBody": {
                    "description": "Login User",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["username", "password"],
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "nozami": {
                                    "description": "Login User Nozami",
                                    "value": {
                                        "username": "nozami",
                                        "password": "password"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Login Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "nama": "nozami",
                                                "username": "nozami",
                                                "token": "10ffe8fd-253c-4cca-af9a-7182e1cabbcb"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Validation Error",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Validation Error",
                                        "value": {
                                            "errors": {
                                                "message": [
                                                    "username or password wrong!"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "tags": ["User"],
                "description": "Get Current user",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Get Current User",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "nama": "nozami",
                                                "username": "nozami",
                                                "token": "10ffe8fd-253c-4cca-af9a-7182e1cabbcb"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "patch": {
                "tags": ["User"],
                "description": "Update user",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "Update User",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["name", "password"],
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "nozami": {
                                    "description": "Update User",
                                    "value": {
                                        "name": "update",
                                        "password": "password"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success Update User",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "nama": "update",
                                                "username": "nozami",
                                                "token": "10ffe8fd-253c-4cca-af9a-7182e1cabbcb"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "delete": {
                "tags": ["User"],
                "description": "Logout user",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "logout success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": true
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            }
        },
        "/category": {
            "get": {
                "tags": ["Category"],
                "description": "Get All Category",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success Get All Category",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": [
                                                {
                                                    "id": 1,
                                                    "name": "Laravel",
                                                    "slug": "laravel"
                                                },
                                                {
                                                    "id": 2,
                                                    "name": "NestJs",
                                                    "slug": "nestjs"
                                                }
                                            ]
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "Unauthorized": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "post": {
                "tags": ["Category"],
                "description": "create Category",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "description": "Create Category",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "required": ["name"],
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "Laravel": {
                                    "description": "create laravel category",
                                    "value": {
                                        "name": "laravel"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success Create Category",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "name": "Laravel",
                                                "slug": "laravel"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "badRequest": {
                                        "description": "Bad Request",
                                        "value": {
                                            "errors": {
                                                "message": {
                                                    "name" : [
                                                        "The name has already been taken.",
                                                        "The name field is required."
                                                    ]
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "Unauthorized": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            }
        },
        "/category/{idCategory}": {
            "get": {
                "tags": ["Category"],
                "description": "Create Category",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "idCategory",
                        "in": "path",
                        "schema": {
                            "type": "integer"
                        },
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Show Category Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "name": "Laravel",
                                                "slug": "laravel"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "notFound",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "notFound": {
                                        "description": "notFound",
                                        "value": {
                                            "errors": {
                                                "message": [
                                                    "not found!"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            },
            "patch": {
                "tags": ["Category"],
                "description": "Update Category",
                "parameters": [
                    {
                        "name": "api_key",
                        "in": "header",
                        "description": "",
                        "required": false,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "name": "idCategory",
                        "in": "path",
                        "schema": {
                            "type": "integer"
                        },
                        "required": true
                    }
                ],
                "requestBody": {
                    "description": "Update Category",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    }
                                }
                            },
                            "examples": {
                                "Laravel": {
                                    "description": "Update laravel category",
                                    "value": {
                                        "name": "Update"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Update Category Success",
                        "content": {
                            "application/json": {
                                "examples": {
                                    "success": {
                                        "value": {
                                            "data": {
                                                "id": 1,
                                                "name": "Update",
                                                "slug": "update"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "notFound",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "notFound": {
                                        "description": "notFound",
                                        "value": {
                                            "errors": {
                                                "message": [
                                                    "not found!"
                                                ]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "content": {
                            "apllication/json": {
                                "examples": {
                                    "validationError": {
                                        "description": "Unauthorized",
                                        "value": {
                                            "errors": {
                                                "message": ["unauthorized!"]
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "security": [
                    {
                        "api_key": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "api_key": {
                "type": "apiKey",
                "name": "api_key",
                "in": "header"
            }
        }
    }
}
